# Runs all data validation checks
check-all: check-pluslife-checklist

LOCAL_SCHEMA_URL := "https://raine.is/paranoid/"

SCHEMA_OK := "{filename}: schema OK"
DATA_OK   := "{filename}: data   OK"
EXIT_ERR  := "42"
EXIT_LAZY := "47"

check-schema file:
    #!/usr/bin/env python3
    import json
    import yaml
    import jsonschema
    import os
    import sys

    filename = "{{file}}"
    basename, ext = os.path.splitext(filename)
    loader = json.load if ext == 'json' else yaml.safe_load
    data = loader(open(filename))
    if '$schema' in data:
        schema_url = data['$schema']
        if '{{LOCAL_SCHEMA_URL}}' in schema_url:
            schema = os.path.basename(schema_url)
        else:
            print("error: I can't be bothered to download schemas yet", file=sys.stderr)
            exit({{EXIT_LAZY}})
    else:
        print(f"error: {filename}: $schema field missing", file=sys.stderr)
        exit({{EXIT_ERR}})
    schema = json.load(open(schema))
    jsonschema.validate(data, schema)
    print("{{SCHEMA_OK}}".format(filename=filename))

# Checks the Pluslife checklist data
check-pluslife-checklist: (check-schema "pluslife-checklist.yml")
    #!/usr/bin/env python3
    FILE = 'pluslife-checklist.yml'

    import yaml
    data = yaml.safe_load(open(FILE))
    
    # check that all test types have the same number of items in each section
    testtypes = [list(tt.keys())[0] for tt in data['testtypes']]
    checklist = data['checklist']

    for section in checklist:
        section_name = section['title']
        items = section['items']

        counts = {tt: 0 for tt in testtypes}
        for item in items:
            item_stripped = item.strip()
            for tt in testtypes:
                if item_stripped.startswith(f'.{tt}'):
                    counts[tt] += 1

        for tt in testtypes:
            if counts[tt] != counts[testtypes[0]]:
                print(f"Section '{section_name}' has uneven item counts for test type '{tt}': {counts[tt]} != {counts[testtypes[0]]}")
                exit(1)
    print("{{DATA_OK}}".format(filename=FILE))